version: '2.1'

services:
  user-management:
    image: user-management
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./server.ts:/usr/src/app/server.ts
    command: npm run dev